# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.


trigger:
- master

pool:
  vmImage: ubuntu-latest


steps:
  - task: UsePythonVersion@0
    
      
  - script: |
         python -m venv antenv
         source antenv/bin/activate
         python -m pip install --upgrade pip
         pip install setup
         pip install -r requirements.txt
    workingDirectory: '$(System.DefaultWorkingDirectory)'
    displayName: "Install requirements"  
  - task: ArchiveFiles@2
    inputs:
     rootFolderOrFile: '$(Build.SourcesDirectory)'
     includeRootFolder: false
     archiveType: 'zip'
     archiveFile: '$(Build.ArtifactStagingDirectory)/Application$(Build.BuildId).zip'
     replaceExistingArchive: true
     
  - publish: $(Build.ArtifactStagingDirectory)/Application$(Build.BuildId).zip
     displayName:'Upload package'
     artifact:drop
